// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCDsUdlS6TX8RSWAW_EMjSqnMQBpnox8',
    appId: '1:565994743759:web:1af65811d04fb5aef854ba',
    messagingSenderId: '565994743759',
    projectId: 'shantravels-934d0',
    authDomain: 'shantravels-934d0.firebaseapp.com',
    storageBucket: 'shantravels-934d0.appspot.com',
    measurementId: 'G-6HNDHYYTPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4cELbBiNJNbeN32XVKRCuvlrca6bQWlM',
    appId: '1:565994743759:android:d8421b7bb3603f2df854ba',
    messagingSenderId: '565994743759',
    projectId: 'shantravels-934d0',
    storageBucket: 'shantravels-934d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIjkJ51kIHhhWVhrbnNE1-SnLkWlbI64A',
    appId: '1:565994743759:ios:005ca468d3de54adf854ba',
    messagingSenderId: '565994743759',
    projectId: 'shantravels-934d0',
    storageBucket: 'shantravels-934d0.appspot.com',
    iosBundleId: 'com.android.phoenixTravelApp',
  );
}
